name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install UV
      run: pip install uv

    - name: Cache UV dependencies
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --frozen

    - name: Run tests
      run: uv run pytest

    - name: Build Docker image
      run: |
        docker build -t rule-engine .
